title: Steve Jenkins
email: web@skysteve.com
description: >- # this means to ignore newlines until "baseurl:"
  Skysteve Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "skysteve.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: skyste
github_username:  skysteve
linkedin_username: skysteve
permalink: /:year/:month/:day/:title/
date_format: "%Y-%m-%d"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji
#  - jekyll-responsive-image

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span: false
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/